#!usr/bin/sh

alias zrc="nvim ~/.config/zsh/.zshrc"
alias brc="nvim ~/.bashrc"
alias src="source ~/.config/zsh/.zshrc"

alias v="vim"
alias n="nvim"
alias vc='nvim --clean -c "syntax enable | set nu | set mouse=a | set clipboard=unnamed | set expandtab | set autoindent | set shiftwidth=2 | set softtabstop=2 | set tabstop=2 | set smarttab | set scrolloff=4"'

alias cls=clear
alias q=exit
alias at='alacritty-themes'
alias dtf="/usr/bin/git --git-dir=$HOME/.jeno_dotfiles/ --work-tree=$HOME"

alias em="setsid emacs --with-profile doom &> /dev/null"
alias e="setsid emacsclient -s user &> /dev/null"

alias em3="~/emacs_src/emacs/src/emacs"
alias pr="~/emacs_src/emacs/src/emacs --with-profile prot"

alias bty="upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep 'time to empty\|percentage'"
