#!/usr/bin/sh

function zsh_add_file() {
    [ -f "$1" ] && source "$1"
}

function zsh_add_plugin() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then 
        # For plugins
        zsh_add_file "$ZDOTDIR/plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
        zsh_add_file "$ZDOTDIR/plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
        #echo "Hello jenowin, it is sourced!!"
    else
        git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME"
    fi
}


# xorg brightness
function xbr() {
  # set brightness for all x screens that are connected.
  if [ $1 "==" 'a' ]; then
    for screen in $(xrandr |awk '/connected/{if($2 == "connected")print $1}')
    do
      xrandr --output $screen --brightness $2
    done
  else
    xrandr --output $1 --brightness $2
  fi
}

function xrr() {
  xset r rate 350 50
}
