#!/bin/sh
# profile - runs on login
#           read by login shell
#           set environment variables here

# Default programs:
export EDITOR="nvim"
#export TERMINAL="alacritty"
export TERMINAL="xterm"
export BROWSER="brave"
export PATH="$HOME/.config/emacs/profiles/doomemacs/bin/:$PATH"

# XDG base directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# startx "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
# zsh config dir
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
