#!/bin/sh
# profile - runs on login
#           read by login shell
#           set environment variables here

# XDG base directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# this variable is respected by xinit, but not by startx
# instead specify filename as an argument to startx like
# startx "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

# zsh config dir
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
alias vc='nvim --clean -c "syntax enable | set nu | set mouse=a | set clipboard=unnamed | set expandtab | set autoindent | set shiftwidth=2 | set softtabstop=2 | set tabstop=2 | set smarttab | set scrolloff=4"'
alias brc="nvim ~/.bashrc"
alias cls=clear
alias q=exit

alias em="emacs --with-profile jen "
alias emn="emacs --with-profile jen -nw"
alias at='alacritty-themes'
alias df="/usr/bin/git --git-dir=$HOME/.jeno_dotfiles/ --work-tree=$HOME"

