#!/bin/sh

# xinitrc runs automatically when you run startx.

# xrandr --output HDMI-1-0 --mode 1920x1080 --right-of eDP1 --mode 1920x1080
#picom -b --experimental-backends

# set this xwallpaper command last and before executing window manager.
#xwallpaper --output HDMI-1-0 --stretch ~/.local/share/backgrounds/arch2.jpg --output eDP1 --stretch ~/.local/share/backgrounds/arch1.jpg


# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

ssh-agent dwm
# xset r rate 350 50 # will be overwritten
